[package]
name = "rika-vpn"
version = "0.1.4"
description = "RikaVPN - Modern Arabic VPN client for Windows"
authors = ["LazySano <https://x.com/lazysanosky>"]
edition = "2021"

[lib]
name = "rika_vpn_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.7.1", features = [] }

[dependencies]
tauri = { version = "2.12.2", features = [] }
tauri-plugin-opener = "2.7.0"
tauri-plugin-updater = "2.13.2"
tauri-plugin-process = "2.4.0"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1.53.2", features = ["rt-multi-thread", "macros"] }
tracing = "0.1.44"
tracing-appender = "0.2.5"
tracing-subscriber = { version = "0.3", features = ["fmt"] }
thiserror = "2"
boringtun = "0.7.1"
wintun = "0.5.1"
base64 = "0.22"
windows-sys = { version = "0.52", features = [
    "Win32_Foundation",
    "Win32_NetworkManagement_IpHelper",
    "Win32_NetworkManagement_Ndis",
] }
ureq = { version = "2", features = ["json"] }
sha2 = "0.10"
rand = "0.8"
urlencoding = "2"

[profile.release]
codegen-units = 1
lto = true
opt-level = "s"
panic = "abort"
strip = true
